### ISSUE TITLE
Issue with editing numeric values containing decimal places in non-English language

### ISSUE THREAD

**Issue by uli-on** [SamAmco/track-and-graph#14]
Whenever I try to edit a track's numeric value containing decimal places, pressing the ADD button leads to erasing the track's value with a zero. 

This seems to be be due to the different use of dots and commas in structuring numeric values in English-speaking countries compared e.g. to the rest of Europe: I use Android in German, and when I set it to English, editing works OK. For clarity: With my German locale I enter e.g. 2,7, not 2.7. Editing such a 2,7 gives zero. 

Android 6.0.1, Moto G, App version 1.4.4 from F-Droid, German locale

**Comment by SamAmco** [comment]
Hi. Thanks for reporting this. I will try and look into this soon.

**Comment by SamAmco** [comment]
There is now a new version of the app out that should fix this bug. I am pretty sure the bug is fixed so I am going to close the issue. If it occurs again, please let me know and I will re-open it. Thanks for your patience.

**Comment by TFCx** [comment]
Problem is still present in v1.5.1. In my case it's the opposite user manipulation. My locale is french (so comma separation). For text, I got 2 android keyboards configured (english-US, french-France). When using the app & entering a number, the displayed keyboard has a dot separator. So when I input a number like 17.2, it gets converted into 0.

(PS : Seems I finally found the perfect app (clean, UX friendly, open source, fast)! Thank you for this app & for all the work involved!)

**Comment by SamAmco** [comment]
Hmm ok. Thanks for bringing this up I will have to revisit the issue. I'm glad you're enjoying the app :)

**Comment by SamAmco** [comment]
Ok once again I have attempted to fix this problem. The new version should be available on the Play store soon. I will close this issue but if you continue to have problems let me know and I will re-open it. Thanks again for your patience.

**Comment by uli-on** [comment]
This has fixed it for me, thank you :) i.e. I can enter new values and edit imported ones without zero-ing values. What needs testing by others, though, is editing values after an update, without previous exporting from the old version and importing into v1.5.2. I've had to switch over to the G-store app as updating my F-Droid version with the apk from Github was impossible and F-Droid has had no DB update since 10+ days.
